<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>500 – Błąd serwera</title>
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
<div class="error-page error-page--standalone">
    <h1>500</h1>
    <p><?= isset($_SESSION) ? t('error.500') : 'Wewnętrzny błąd serwera.' ?></p>
    <a href="/" class="btn">Wróć na stronę główną</a>
    <p>Ekipa sprytnych szympansów pracuje nad rozwiązaniem problemu, jakbyś je widział podaj im ten kod: </a>
    <p>AIOUGsuiir3r0909avda=-ASfpAOr3AIOj30q[jAIO[jr23[q0fcj[a)JIOFAj@#0jadfpasjfF_RJKvo-a[</p>
</div>
</body>
</html>
